language: python3

before_install:
        - sudo apt remove -y docker-compose  
        - sudo apt install -y docker-compose 
        
install:
        - pip install -r requirements.txt
        
service:
        - docker 
        
script:
        - docker-compose --version
        - make test
