version: "3.7"

services:
    balancer:
        image: "electricrainbow/pm-balancer-server-image:${BALANCER_VERSION}"
        build:
            context: .
            dockerfile: Dockerfile_balancer
    server:
        image: "electricrainbow/pm-default-server-image:${SERVER_VERSION}"
        build:
            context: .
            dockerfile: Dockerfile_server
