version: "3.7"

services:
    controller:
        image: electricrainbow/pm-default-server-image:${SERVER_VERSION}
        container_name: pm-default-server-container
        ports:
          - ${PORT}:${PORT}
        depends_on:
          - service
        networks:
          - pm-network
        depends_on:
          - redis
          - mongo
        env_file: .env
    redis:
        image: redis
        container_name: redis
        networks:
          - pm-network
    mongo:
        image: mongo
        container_name: mongo
        networks:
          - pm-network

networks:
    pm-network:
