version: "3.7"

services:
    balancer:
        image: electricrainbow/pm-balancer-server-image:${BALANCER_VERSION}
        ports:
          - ${BALANCER_PORT}:${BALANCER_PORT}
        depends_on:
          - server1
          - server2
        networks:
          - pm-network
        environment:
          - PORT=${BALANCER_PORT}
          - INSTANCE_COUNT=${INSTANCE_COUNT}
    server1:
        image: electricrainbow/pm-default-server-image:${SERVER_VERSION}
        container_name: pm-default-server-container-1
        ports:
          - "${SERVER1_PORT}"
        networks:
          - pm-network
        depends_on:
          - redis1
          - mongo
        environment:
          - PORT=${SERVER1_PORT}
          - REDIS_PORT=${REDIS1_PORT}
          - REDIS_HOST=redis1
    server2:
        image: electricrainbow/pm-default-server-image:${SERVER_VERSION}
        container_name: pm-default-server-container-2
        ports:
          - "${SERVER2_PORT}"
        networks:
          - pm-network
        depends_on:
          - redis2
          - mongo
        environment:
          - PORT=${SERVER2_PORT}
          - REDIS_PORT=${REDIS2_PORT}
          - REDIS_HOST=redis2
    redis1:
        image: redis
        container_name: redis1
        ports:
          - "6379"
        command: --port 6379
        networks:
          - pm-network
    redis2:
        image: redis
        container_name: redis2
        ports:
          - "6380"
        command: --port 6380
        networks:
          - pm-network
    mongo:
        image: mongo
        container_name: mongo
        networks:
          - pm-network

networks:
    pm-network:
